### ISSUE TITLE
There is no index.js in this project

### ISSUE THREAD

**Issue by idkjs** [callstackincubator/bs-react-navigation#12]
https://github.com/callstackincubator/bs-react-navigation/blob/76d85c47b69aa52534c1a1f44ab6c41c72dac006/example/src/App.re#L42

**Comment by czystyl** [comment]
Thanks, @idkjs for your feedback! 

You are right that message is a little confusing. The example app is base on the Expo so the entry point is here: 

https://github.com/callstackincubator/bs-react-navigation/blob/master/example/App.js
