### ISSUE TITLE
Update readme with example and explanations

### ISSUE THREAD

**Issue by czystyl** [callstackincubator/bs-react-navigation#20]
- [x] Instruction about instalation
- [x] Example how to use the navigator inside the project
- [x] Know issues - like nested navigators

**Comment by MoOx** [comment]
It seems (except Known issues) that doc is almost ok, at least for an alpha. Would you up to cut a release with that?

**Comment by czystyl** [comment]
Yep, I forgot about it but we can release it.

**Comment by czystyl** [comment]
```bs-react-navigation 0.2.0 published 🎉```

**Comment by MoOx** [comment]
Thank you! 🥳
