### ISSUE TITLE
BsReactNavigation module

### ISSUE THREAD

**Issue by idkjs** [callstackincubator/bs-react-navigation#30]
Where is the BsReactNavigation module defined that we call when we use `open BsReactNavigation?

**Comment by MoOx** [comment]
It comes from this 
https://github.com/callstackincubator/bs-react-navigation/blob/64262c01aba43e4294e15409a99320d4b5740649/bsconfig.json#L9

bs assume a name from this flag & use "name" to camelCase.

**Comment by idkjs** [comment]
@MoOx Thank you, sir. namespace based on the name in bsconfig.json. Got it.
