### ISSUE TITLE
Import on React Reason App

### ISSUE THREAD

**Issue by muhammadridho** [callstackincubator/bs-react-navigation#31]
in example we directly render to App.js (Not React Reason Component ), but how do I put it to react react native reason component ?

**Comment by czystyl** [comment]
`App.js` file is the first file that needs to be a JS file. You can start your hacking inside `example/src/App.re`.

**Comment by muhammadridho** [comment]
can you give an example ?, what I want here is 

```
<Provider>
   <Routes> -> Route.render or whatever who wrap routing
</Provider>
```

**Comment by czystyl** [comment]
@muhammadridho Please come to the Discord channel, I can help you there :) 

Here is the link: https://discord.gg/s7RHAF
