### ISSUE TITLE
Transfert this repo to reasonml-community

### ISSUE THREAD

**Issue by MoOx** [callstackincubator/bs-react-navigation#33]
It seems this repo is kind of neglected.
Would you be open to transfer it to reasonml-community?

A work as been done in another repo (https://github.com/cca-io/bs-react-navigation/tree/hooks) but I think we should concentrate the effort. A lot of people find this repo & struggle to use it (as it's atm a total wip ^^).

Thanks in advance for considering this.

(If you are ok for this, you could transfer repo to @anmonteiro that should have the proper right to transfert it back to reasonml-community.)

Also adding someone to npm could be nice (eg: me: ~moox on npm)

**Comment by czystyl** [comment]
We think about it some time ago but definitely, need to wait when @grabbou do a decision regarding the transfer. 

CC @grabbou Let me know, I can do this because of my admin permissions here.

**Comment by grabbou** [comment]
I would be happy to transfer it but I think that our approach here was a bit different from just providing bindings - it was all about creating a custom wrapper from the very first day.

The linked repository seems different. 

That said, I'd rather archive this one since it's not under heavy development, but I wouldn't necessarily get rid of this approach.

**Comment by MoOx** [comment]
In this case the name prefixed by bs- isn't appropriate as this suffix is (in theory) for pure bindings only.
Anyway, bs-react-native being renamed reason-react-native soon, we will go with the same prefix for incoming bindings...

**Comment by grabbou** [comment]
> In this case the name prefixed by bs- isn't appropriate as this suffix is (in theory) for pure bindings only.

Right. Let me do something with the repo so it doesn't confuse anyone. Happy to give `npm` rights tho.
